services:
  stats-server:
    build: ./stats/stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_db
      - SPRING_DATASOURCE_USERNAME=stats_db_user
      - SPRING_DATASOURCE_PASSWORD=stats_db_password
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9090/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  stats-db:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=stats_db_user
      - POSTGRES_PASSWORD=stats_db_password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats_db_user -d stats_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-service:
    build: ./ewm-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_db
      - SPRING_DATASOURCE_USERNAME=ewm_db_user
      - SPRING_DATASOURCE_PASSWORD=ewm_db_password
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=ewm_db_user
      - POSTGRES_PASSWORD=ewm_db_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ewm_db_user -d ewm_db"]
      interval: 5s
      timeout: 5s
      retries: 10